// ============================================================================
// .neon DSL — Rust code generator
// ============================================================================
//
// Emits a `reducers.rs` file using `#[neondb::reducer]` macros.
//
// Symbol table tracks:
//   Param(ty)          — reducer parameter with known Neon type
//   RowBinding(table)  — bound by `let x = table[key]` or for-loop val
//   Local              — bound by `let x = expr`

use super::ast::*;
use super::error::NeonError;
use std::collections::HashMap;

// ── Symbol table ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
enum Binding {
    #[allow(dead_code)]
    Param(Type),
    RowBinding(String),
    Local,
}

struct Scope<'a> {
    vars:   HashMap<String, Binding>,
    tables: &'a [TableDecl],
}

impl<'a> Scope<'a> {
    fn new(tables: &'a [TableDecl]) -> Self {
        Scope { vars: HashMap::new(), tables }
    }

    fn child(&self) -> Scope<'_> {
        Scope { vars: self.vars.clone(), tables: self.tables }
    }

    fn add(&mut self, name: &str, binding: Binding) {
        self.vars.insert(name.to_owned(), binding);
    }

    fn get(&self, name: &str) -> Option<&Binding> {
        self.vars.get(name)
    }

    fn field_type(&self, table_name: &str, field_name: &str) -> Option<&Type> {
        self.tables.iter()
            .find(|t| t.name == table_name)?
            .fields.iter()
            .find(|f| f.name == field_name)
            .map(|f| &f.ty)
    }
}

// ── Public entry point ────────────────────────────────────────────────────────

pub fn generate(program: &Program) -> Result<String, NeonError> {
    let mut out = String::new();

    out.push_str("// Auto-generated by the NeonDB .neon compiler. Do not edit.\n\n");
    out.push_str("#![allow(unused_variables, dead_code, unused_mut)]\n");
    out.push_str("use neondb::reducer::context::ReducerContext;\n\n");

    for reducer in &program.reducers {
        let mut scope = Scope::new(&program.tables);
        for p in &reducer.params {
            scope.add(&p.name, Binding::Param(p.ty.clone()));
        }
        out.push_str(&gen_reducer(reducer, &mut scope)?);
        out.push('\n');
    }

    Ok(out)
}

// ── Reducer ───────────────────────────────────────────────────────────────────

fn gen_reducer(r: &ReducerDecl, scope: &mut Scope) -> Result<String, NeonError> {
    let mut out = String::new();

    out.push_str("#[neondb::reducer]\n");
    // A reducer may legitimately be named after a Rust keyword (e.g. `move`,
    // `type`, `match`). Escape it as a raw identifier so the generated Rust
    // compiles; the `#[neondb::reducer]` macro strips the `r#` back off when it
    // derives the wire name, so clients still call it by its plain Neon name.
    out.push_str(&format!("fn {}(ctx: ReducerContext", escape_rust_keyword(&r.name)));
    for p in &r.params {
        out.push_str(&format!(", {}: {}", p.name, p.ty.to_rust()));
    }
    out.push_str(") {\n");

    for stmt in &r.body {
        out.push_str(&gen_stmt(stmt, scope, 1)?);
    }

    out.push_str("}\n");
    Ok(out)
}

/// Wrap a name in `r#` if it collides with a Rust keyword, so it can be used
/// as a Rust identifier. The handful of keywords that cannot be raw identifiers
/// (`crate`, `self`, `Self`, `super`) are left unchanged — they are not valid
/// Neon reducer names in practice.
fn escape_rust_keyword(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "dyn", "else", "enum", "extern",
        "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
        "move", "mut", "pub", "ref", "return", "static", "struct", "trait",
        "true", "type", "unsafe", "use", "where", "while", "async", "await",
        "abstract", "become", "box", "do", "final", "macro", "override", "priv",
        "typeof", "unsized", "virtual", "yield", "try",
    ];
    if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

// ── Statements ────────────────────────────────────────────────────────────────

fn gen_stmt(stmt: &Stmt, scope: &mut Scope, indent: usize) -> Result<String, NeonError> {
    let pad = "    ".repeat(indent);
    match stmt {

        // ── let p = players[id] else { ... } ─────────────────────────────────
        Stmt::LetRow { name, table, key, else_body, line: _ } => {
            scope.add(name, Binding::RowBinding(table.clone()));
            let key_code = gen_expr(key, scope);
            let mut out = format!(
                "{pad}let mut {name} = match ctx.get({table:?}, &({key_code}).to_string())? {{\n\
                 {pad}    Some(v) => v,\n\
                 {pad}    None => {{\n"
            );
            if let Some(body) = else_body {
                for s in body {
                    out.push_str(&gen_stmt(s, scope, indent + 2)?);
                }
                out.push_str(&format!("{pad}        return Ok(vec![]);\n"));
            } else {
                out.push_str(&format!(
                    "{pad}        return Err(neondb::error::NeonDBError::reducer_error(\
                     \"Row not found in {table}\"));\n"
                ));
            }
            out.push_str(&format!("{pad}    }}\n{pad}}};\n"));
            Ok(out)
        }

        // ── let x = expr ─────────────────────────────────────────────────────
        Stmt::Let { name, value, .. } => {
            scope.add(name, Binding::Local);
            let v = gen_expr(value, scope);
            Ok(format!("{pad}let mut {name} = {v};\n"))
        }

        // ── name = expr (reassign existing local) ─────────────────────────────
        Stmt::Assign { name, value, .. } => {
            let v = gen_expr(value, scope);
            Ok(format!("{pad}{name} = {v};\n"))
        }

        // ── players[id] = { ... } ─────────────────────────────────────────────
        Stmt::AssignRow { table, key, value, .. } => {
            let k = gen_expr(key, scope);
            let v = gen_row_expr(value, scope);
            Ok(format!("{pad}ctx.set({table:?}, &({k}).to_string(), {v})?;\n"))
        }

        // ── players[id].field = expr ──────────────────────────────────────────
        Stmt::AssignField { table, key, field, value, line: _ } => {
            let k = gen_expr(key, scope);
            let v = gen_expr(value, scope);
            let field_ty = scope.field_type(table, field).cloned().unwrap_or(Type::Str);
            let json_val = coerce_to_json(&v, &field_ty);
            let tmp = format!("__row_{field}_{}", scope.vars.len());
            Ok(format!(
                "{pad}{{\n\
                 {pad}    let mut {tmp} = ctx.get({table:?}, &({k}).to_string())?\
                         .unwrap_or_else(|| serde_json::json!({{}}));\n\
                 {pad}    {tmp}[{field:?}] = {json_val};\n\
                 {pad}    ctx.set({table:?}, &({k}).to_string(), {tmp})?;\n\
                 {pad}}}\n"
            ))
        }

        // ── players[id].hp += amt ─────────────────────────────────────────────
        Stmt::AssignFieldOp { table, key, field, op, value, line: _ } => {
            let k = gen_expr(key, scope);
            let v = gen_expr(value, scope);
            let field_ty = scope.field_type(table, field).cloned().unwrap_or(Type::Int);
            let getter  = field_getter_code(&field_ty);
            let zero    = field_ty.zero_rust();
            let rust_op = op.to_rust();
            let json_val = coerce_to_json(
                &format!("(__old_{field} {rust_op} ({v}))"),
                &field_ty,
            );
            let tmp = format!("__row_{field}_{}", scope.vars.len());
            Ok(format!(
                "{pad}{{\n\
                 {pad}    let mut {tmp} = ctx.get({table:?}, &({k}).to_string())?\
                         .unwrap_or_else(|| serde_json::json!({{}}));\n\
                 {pad}    let __old_{field} = {tmp}[{field:?}].{getter}.unwrap_or({zero});\n\
                 {pad}    {tmp}[{field:?}] = {json_val};\n\
                 {pad}    ctx.set({table:?}, &({k}).to_string(), {tmp})?;\n\
                 {pad}}}\n"
            ))
        }

        // ── delete players[id] ────────────────────────────────────────────────
        Stmt::DeleteRow { table, key, .. } => {
            let k = gen_expr(key, scope);
            Ok(format!("{pad}ctx.delete({table:?}, &({k}).to_string())?;\n"))
        }

        // ── if cond { ... } else if ... | else { ... } ────────────────────────
        Stmt::If { condition, then_body, else_body, .. } => {
            let cond = gen_bool_expr(condition, scope);
            let mut out = format!("{pad}if {cond} {{\n");
            let mut child = scope.child();
            for s in then_body {
                out.push_str(&gen_stmt(s, &mut child, indent + 1)?);
            }
            if let Some(eb) = else_body {
                // `else if` sugar: single If stmt in the else body
                if eb.len() == 1 {
                    if let Stmt::If { condition: ec, then_body: et, else_body: ee, .. } = &eb[0] {
                        let econd = gen_bool_expr(ec, scope);
                        out.push_str(&format!("{pad}}} else if {econd} {{\n"));
                        let mut child2 = scope.child();
                        for s in et { out.push_str(&gen_stmt(s, &mut child2, indent + 1)?); }
                        if let Some(eeb) = ee {
                            out.push_str(&format!("{pad}}} else {{\n"));
                            let mut child3 = scope.child();
                            for s in eeb { out.push_str(&gen_stmt(s, &mut child3, indent + 1)?); }
                        }
                        out.push_str(&format!("{pad}}}\n"));
                        return Ok(out);
                    }
                }
                out.push_str(&format!("{pad}}} else {{\n"));
                let mut child2 = scope.child();
                for s in eb {
                    out.push_str(&gen_stmt(s, &mut child2, indent + 1)?);
                }
            }
            out.push_str(&format!("{pad}}}\n"));
            Ok(out)
        }

        // ── for id, p in players { ... } ─────────────────────────────────────
        Stmt::ForRow { key_var, val_var, table, body, .. } => {
            let mut out = format!(
                "{pad}for ({key_var}, {val_var}) in ctx.tables.list_rows_with_keys({table:?})? {{\n"
            );
            let mut child = scope.child();
            child.add(key_var, Binding::Local);
            child.add(val_var, Binding::RowBinding(table.clone()));
            for s in body {
                out.push_str(&gen_stmt(s, &mut child, indent + 1)?);
            }
            out.push_str(&format!("{pad}}}\n"));
            Ok(out)
        }

        // ── for item in arr_expr { ... } ─────────────────────────────────────
        Stmt::ForArray { item_var, array, body, .. } => {
            let arr = gen_expr(array, scope);
            let tmp = format!("__arr_{item_var}_{}", scope.vars.len());
            let mut out = format!(
                "{pad}let {tmp} = ({arr}).as_array().cloned().unwrap_or_default();\n\
                 {pad}for {item_var} in {tmp} {{\n"
            );
            let mut child = scope.child();
            child.add(item_var, Binding::Local);
            for s in body {
                out.push_str(&gen_stmt(s, &mut child, indent + 1)?);
            }
            out.push_str(&format!("{pad}}}\n"));
            Ok(out)
        }

        // ── while cond { ... } ────────────────────────────────────────────────
        Stmt::While { condition, body, .. } => {
            let cond = gen_bool_expr(condition, scope);
            let mut out = format!("{pad}while {cond} {{\n");
            let mut child = scope.child();
            for s in body {
                out.push_str(&gen_stmt(s, &mut child, indent + 1)?);
            }
            out.push_str(&format!("{pad}}}\n"));
            Ok(out)
        }

        // ── break / continue ──────────────────────────────────────────────────
        Stmt::Break    { .. } => Ok(format!("{pad}break;\n")),
        Stmt::Continue { .. } => Ok(format!("{pad}continue;\n")),

        // ── return { ok: true } ───────────────────────────────────────────────
        Stmt::Return { value, .. } => {
            let v = gen_return_expr(value, scope);
            Ok(format!("{pad}neondb::ret!({v});\n"))
        }

        // ── error("msg") ──────────────────────────────────────────────────────
        Stmt::Error { message, .. } => {
            Ok(format!(
                "{pad}return Err(neondb::error::NeonDBError::reducer_error({message:?}));\n"
            ))
        }

        // ── set_counter("kills", val) / push(arr, val) / ... ─────────────────
        Stmt::CallStmt { name, args, .. } => {
            gen_call_stmt(name, args, scope, &pad)
        }
    }
}

// ── Built-in call statements ──────────────────────────────────────────────────

fn gen_call_stmt(name: &str, args: &[Expr], scope: &Scope, pad: &str) -> Result<String, NeonError> {
    let a = |i: usize| args.get(i).map(|e| gen_expr(e, scope)).unwrap_or_default();
    match name {
        "set_counter" => {
            let n = a(0);
            let v = a(1);
            Ok(format!("{pad}ctx.set_counter(({n}).to_string(), ({v}) as i32)?;\n"))
        }

        // ── Array mutation stmts ──────────────────────────────────────────────
        "push" => {
            let arr = a(0);
            let val = a(1);
            Ok(format!(
                "{pad}if let serde_json::Value::Array(ref mut __push_v) = {arr} {{\n\
                 {pad}    __push_v.push(serde_json::json!(({val})));\n\
                 {pad}}}\n"
            ))
        }
        "pop" => {
            let arr = a(0);
            Ok(format!(
                "{pad}if let serde_json::Value::Array(ref mut __pop_v) = {arr} {{\n\
                 {pad}    __pop_v.pop();\n\
                 {pad}}}\n"
            ))
        }
        "remove_at" => {
            let arr = a(0);
            let idx = a(1);
            Ok(format!(
                "{pad}if let serde_json::Value::Array(ref mut __rm_v) = {arr} {{\n\
                 {pad}    let __rm_idx = ({idx}) as usize;\n\
                 {pad}    if __rm_idx < __rm_v.len() {{ __rm_v.remove(__rm_idx); }}\n\
                 {pad}}}\n"
            ))
        }

        other => {
            // Generic function call statement (result ignored).
            let arg_code: Vec<_> = args.iter().map(|e| gen_expr(e, scope)).collect();
            Ok(format!("{pad}{};\n", gen_builtin_call(other, &arg_code)))
        }
    }
}

// ── Expressions ───────────────────────────────────────────────────────────────

fn gen_expr(expr: &Expr, scope: &Scope) -> String {
    match expr {
        Expr::Lit(lit) => gen_literal(lit),

        Expr::Var(name) => match name.as_str() {
            "caller_id"   => "ctx.caller_id.clone()".to_owned(),
            "caller_role" => "ctx.caller_role.clone()".to_owned(),
            _ => {
                if let Some(Binding::Param(Type::Str)) = scope.get(name) {
                    format!("{name}.clone()")
                } else {
                    name.clone()
                }
            }
        },

        Expr::RowRead { table, key } => {
            let k = gen_expr(key, scope);
            format!("ctx.get({table:?}, &({k}).to_string())?.unwrap_or_else(|| serde_json::json!({{}}))")
        }

        Expr::FieldAccess { object, field } => {
            let obj    = gen_expr(object, scope);
            let getter = infer_field_getter(object, field, scope);
            format!("{obj}[{field:?}].{getter}")
        }

        Expr::RowLiteral { fields } => {
            let parts: Vec<_> = fields.iter()
                .map(|(k, v)| format!("{k:?}: {}", gen_json_val(v, scope)))
                .collect();
            format!("serde_json::json!({{ {} }})", parts.join(", "))
        }

        Expr::ArrayLit(elems) => {
            let parts: Vec<_> = elems.iter()
                .map(|e| format!("serde_json::json!(({})) ", gen_expr(e, scope)))
                .collect();
            format!("serde_json::Value::Array(vec![{}])", parts.join(", "))
        }

        Expr::BinOp { left, op, right } => {
            let l = gen_expr(left, scope);
            let r = gen_expr(right, scope);
            format!("({l} {} {r})", op.to_rust())
        }

        Expr::Not(inner) => format!("!({})", gen_expr(inner, scope)),

        Expr::FnCall { name, args } => {
            let arg_code: Vec<_> = args.iter().map(|a| gen_expr(a, scope)).collect();
            gen_builtin_call(name, &arg_code)
        }
    }
}

/// Generate a bool-typed expression, unwrapping JSON booleans where needed.
fn gen_bool_expr(expr: &Expr, scope: &Scope) -> String {
    gen_expr(expr, scope)
}

// ── Built-in function calls ───────────────────────────────────────────────────

fn gen_builtin_call(name: &str, args: &[String]) -> String {
    let a = |i: usize| args.get(i).cloned().unwrap_or_else(|| "()".to_owned());

    match name {
        // ── Time ─────────────────────────────────────────────────────────────
        "timestamp"   => "(ctx.timestamp() as i64)".to_owned(),

        // ── Counters ─────────────────────────────────────────────────────────
        "counter"     => format!("ctx.get_counter(&({}).to_string()).ok().flatten().map(|__c| __c.value as i64).unwrap_or(0i64)", a(0)),

        // ── Math ─────────────────────────────────────────────────────────────
        "min"         => format!("({}).min({})", a(0), a(1)),
        "max"         => format!("({}).max({})", a(0), a(1)),
        "abs"         => format!("({}).abs()", a(0)),
        "floor"       => format!("({} as f64).floor()", a(0)),
        "ceil"        => format!("({} as f64).ceil()", a(0)),
        "sqrt"        => format!("({} as f64).sqrt()", a(0)),
        "pow"         => format!("({} as f64).powf({} as f64)", a(0), a(1)),
        "clamp"       => format!("({}).clamp({}, {})", a(0), a(1), a(2)),
        "sign"        => format!("{{ let __sv = {} as f64; if __sv > 0.0 {{ 1i64 }} else if __sv < 0.0 {{ -1i64 }} else {{ 0i64 }} }}", a(0)),
        "round"       => format!("({} as f64).round() as i64", a(0)),
        "log2"        => format!("({} as f64).log2()", a(0)),
        "log10"       => format!("({} as f64).log10()", a(0)),

        // ── Random (timestamp-seeded, no external dep) ────────────────────────
        "rand_int"    => format!(
            "{{ let __ts = ctx.timestamp(); let __lo = {} as i64; let __hi = {} as i64; \
             let __r = (__ts ^ (__ts >> 33)) % ((__hi - __lo + 1).max(1) as u64); \
             __lo + __r as i64 }}",
            a(0), a(1)
        ),
        "rand_float"  => "{ let __ts = ctx.timestamp(); \
             ((__ts ^ (__ts >> 33)) % 1_000_000u64) as f64 / 1_000_000.0f64 }".to_string(),

        // ── Type casts ───────────────────────────────────────────────────────
        "str"         => format!("({}).to_string()", a(0)),
        "int"         => format!("({}) as i64", a(0)),
        "float"       => format!("({}) as f64", a(0)),
        "bool"        => format!("({}) != 0", a(0)),

        // ── String operations ────────────────────────────────────────────────
        "len"         => format!("({}).len() as i64", a(0)),
        "concat"      => format!("format!(\"{{}}{{}}\" , {}, {})", a(0), a(1)),
        "contains"    => format!("({}).contains(&*({}))", a(0), a(1)),
        "starts_with" => format!("({}).starts_with(&*({}))", a(0), a(1)),
        "ends_with"   => format!("({}).ends_with(&*({}))", a(0), a(1)),
        "to_upper"    => format!("({}).to_uppercase()", a(0)),
        "to_lower"    => format!("({}).to_lowercase()", a(0)),
        "trim"        => format!("({}).trim().to_owned()", a(0)),
        "replace"     => format!("({}).replace(&*({}) as &str, &*({}) as &str)", a(0), a(1), a(2)),
        "substring"   => format!(
            "({}).chars().skip(({}) as usize).take((({}) - ({}) as i64).max(0) as usize).collect::<String>()",
            a(0), a(1), a(2), a(1)
        ),
        "index_of"    => format!("({}).find(&*({}) as &str).map(|__i| __i as i64).unwrap_or(-1i64)", a(0), a(1)),
        "split"       => format!(
            "serde_json::Value::Array(({}).split(&*({}) as &str)\
             .map(|__s| serde_json::Value::String(__s.to_owned())).collect::<Vec<_>>())",
            a(0), a(1)
        ),
        "join"        => format!(
            "({}).as_array().map(|__v| __v.iter()\
             .map(|__x| __x.as_str().unwrap_or(\"\").to_owned())\
             .collect::<Vec<_>>().join(&*({}) as &str)).unwrap_or_default()",
            a(0), a(1)
        ),
        "parse_int"   => format!("({}).parse::<i64>().unwrap_or(0i64)", a(0)),
        "parse_float" => format!("({}).parse::<f64>().unwrap_or(0.0f64)", a(0)),
        "char_at"     => format!(
            "({}).chars().nth(({}) as usize)\
             .map(|__c| __c.to_string()).unwrap_or_default()",
            a(0), a(1)
        ),
        "repeat"      => format!("({}).repeat(({}) as usize)", a(0), a(1)),

        // ── Array operations (expressions) ────────────────────────────────────
        "array_len"     => format!("({}).as_array().map(|__v| __v.len() as i64).unwrap_or(0i64)", a(0)),
        "get_index"     => format!(
            "({}).as_array().and_then(|__v| __v.get(({}) as usize)).cloned()\
             .unwrap_or(serde_json::Value::Null)",
            a(0), a(1)
        ),
        "array_contains" => format!(
            "({}).as_array().map(|__v| __v.contains(&serde_json::json!(({})))) .unwrap_or(false)",
            a(0), a(1)
        ),
        "slice"         => format!(
            "serde_json::Value::Array(\
             ({}).as_array().map(|__v| __v[({}) as usize..({}).min(__v.len() as i64) as usize].to_vec())\
             .unwrap_or_default())",
            a(0), a(1), a(2)
        ),
        "array_first"   => format!(
            "({}).as_array().and_then(|__v| __v.first()).cloned().unwrap_or(serde_json::Value::Null)",
            a(0)
        ),
        "array_last"    => format!(
            "({}).as_array().and_then(|__v| __v.last()).cloned().unwrap_or(serde_json::Value::Null)",
            a(0)
        ),
        "array_reverse" => format!(
            "{{ let mut __rv = ({}).as_array().cloned().unwrap_or_default(); __rv.reverse(); serde_json::Value::Array(__rv) }}",
            a(0)
        ),

        // ── Table query builtins ───────────────────────────────────────────────
        "count_rows"  => format!(
            "(ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default().len() as i64)",
            a(0)
        ),
        "sum_field"   => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             __rows.iter().map(|(_, __r)| __r[__field.as_str()].as_f64().unwrap_or(0.0)).sum::<f64>() }}",
            a(0), a(1)
        ),
        "avg_field"   => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             let __n = __rows.len() as f64; \
             if __n > 0.0 {{ \
               __rows.iter().map(|(_, __r)| __r[__field.as_str()].as_f64().unwrap_or(0.0)).sum::<f64>() / __n \
             }} else {{ 0.0f64 }} }}",
            a(0), a(1)
        ),
        "min_field"   => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             __rows.iter().map(|(_, __r)| __r[__field.as_str()].as_f64().unwrap_or(f64::MAX)) \
               .fold(f64::MAX, f64::min) }}",
            a(0), a(1)
        ),
        "max_field"   => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             __rows.iter().map(|(_, __r)| __r[__field.as_str()].as_f64().unwrap_or(f64::MIN)) \
               .fold(f64::MIN, f64::max) }}",
            a(0), a(1)
        ),
        "find_first"  => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             let __val = serde_json::json!(({})  ); \
             __rows.into_iter().find(|(_, __r)| __r[__field.as_str()] == __val) \
               .map(|(_, __r)| __r).unwrap_or(serde_json::Value::Null) }}",
            a(0), a(1), a(2)
        ),
        "find_all"    => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             let __val = serde_json::json!(({})  ); \
             serde_json::Value::Array(__rows.into_iter() \
               .filter(|(_, __r)| __r[__field.as_str()] == __val) \
               .map(|(_, __r)| __r).collect()) }}",
            a(0), a(1), a(2)
        ),
        "sort_by"     => format!(
            "{{ let mut __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             let __dir = ({}).to_string(); \
             __rows.sort_by(|(_, __a), (_, __b)| {{ \
               let __av = &__a[__field.as_str()]; let __bv = &__b[__field.as_str()]; \
               if __av.is_f64() || __av.is_i64() || __av.is_u64() {{ \
                 __av.as_f64().unwrap_or(0.0).partial_cmp(&__bv.as_f64().unwrap_or(0.0)) \
                   .unwrap_or(std::cmp::Ordering::Equal) \
               }} else {{ \
                 __av.as_str().unwrap_or(\"\").cmp(__bv.as_str().unwrap_or(\"\")) \
               }} \
             }}); \
             if __dir == \"desc\" {{ __rows.reverse(); }} \
             serde_json::Value::Array(__rows.into_iter().map(|(_, __r)| __r).collect()) }}",
            a(0), a(1), a(2)
        ),
        "top_n"       => format!(
            "{{ let mut __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             let __field = ({}).to_string(); \
             let __n = ({}) as usize; \
             __rows.sort_by(|(_, __a), (_, __b)| {{ \
               let __av = &__a[__field.as_str()]; let __bv = &__b[__field.as_str()]; \
               __bv.as_f64().unwrap_or(0.0).partial_cmp(&__av.as_f64().unwrap_or(0.0)) \
                 .unwrap_or(std::cmp::Ordering::Equal) \
             }}); \
             serde_json::Value::Array(__rows.into_iter().take(__n).map(|(_, __r)| __r).collect()) }}",
            a(0), a(1), a(2)
        ),
        "keys_of"     => format!(
            "{{ let __rows = ctx.tables.list_rows_with_keys(&*({}) as &str).unwrap_or_default(); \
             serde_json::Value::Array(__rows.into_iter() \
               .map(|(k, _)| serde_json::Value::String(k)).collect()) }}",
            a(0)
        ),

        // ── Row existence check ───────────────────────────────────────────────
        "exists"      => format!("ctx.get(&({}), &({}).to_string())?.is_some()", a(0), a(1)),

        // ── Cluster-aware primitives ──────────────────────────────────────────

        // cluster_route(key) → u32 shard/cluster ID that owns this key.
        // In single-node mode always returns 0.
        // In consistent-hash mode returns a stable numeric ID for the owning cluster.
        "cluster_route" => format!(
            "(neondb::cluster::cluster_shard_for_key(&({}).to_string()) as i64)",
            a(0)
        ),

        // cross_cluster_call(shard_id, reducer_name, args_json)
        // → forwards a reducer call to the owning shard, returns response bytes as a str.
        // The reducer runs remotely; the result is the raw JSON response.
        "cross_cluster_call" => format!(
            "{{ \
             let __cc_bytes = neondb::cluster::proxy_call_global(\
               ({}) as u32, \
               &({}).to_string(), \
               &({}).to_string(), \
               &ctx.caller_id, \
               &ctx.caller_role\
             ); \
             String::from_utf8_lossy(&__cc_bytes).to_string() \
             }}",
            a(0), a(1), a(2)
        ),

        // region_count_rows(table) → i64 total rows across ALL clusters.
        // Queries every healthy peer via HTTP and sums up their local counts.
        "region_count_rows" => format!(
            "{{ \
             let __local_n = ctx.tables.list_rows_with_keys(&({}).to_string()).unwrap_or_default().len() as i64; \
             neondb::cluster::region_count_rows_global(&({}).to_string(), __local_n) \
             }}",
            a(0), a(0)
        ),

        // migrate_to_cluster(table, key, shard_id)
        // → moves row to a specific cluster and deletes it locally. Returns bool.
        "migrate_to_cluster" => format!(
            "{{ \
             let __mt_data = ctx.get(&({}).to_string(), &({}).to_string())?; \
             let __mt_ok = neondb::cluster::migrate_row_global(\
               &({}).to_string(), \
               &({}).to_string(), \
               ({}) as u32, \
               __mt_data\
             ); \
             if __mt_ok {{ ctx.delete(&({}).to_string(), &({}).to_string())?; }} \
             __mt_ok \
             }}",
            a(0), a(1), a(0), a(1), a(2), a(0), a(1)
        ),

        // ── Unknown — emit as-is and let rustc catch it ───────────────────────
        other => {
            let joined = args.join(", ");
            format!("{other}({joined})")
        }
    }
}

// ── Expression helpers ────────────────────────────────────────────────────────

fn gen_row_expr(expr: &Expr, scope: &Scope) -> String {
    match expr {
        Expr::RowLiteral { fields } => {
            let parts: Vec<_> = fields.iter()
                .map(|(k, v)| format!("{k:?}: {}", gen_json_val(v, scope)))
                .collect();
            format!("serde_json::json!({{ {} }})", parts.join(", "))
        }
        other => gen_expr(other, scope),
    }
}

fn gen_return_expr(expr: &Expr, scope: &Scope) -> String {
    match expr {
        Expr::RowLiteral { fields } => {
            let parts: Vec<_> = fields.iter()
                .map(|(k, v)| format!("{k:?}: {}", gen_json_val(v, scope)))
                .collect();
            format!("{{ {} }}", parts.join(", "))
        }
        other => gen_expr(other, scope),
    }
}

fn gen_json_val(expr: &Expr, scope: &Scope) -> String {
    match expr {
        Expr::Lit(lit) => gen_literal(lit),
        other => format!("({})", gen_expr(other, scope)),
    }
}

fn gen_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(n)   => format!("{n}i64"),
        Literal::Float(f) => format!("{f}f64"),
        Literal::Str(s)   => format!("{s:?}.to_owned()"),
        Literal::Bool(b)  => format!("{b}"),
    }
}

/// JSON getter expression for a typed field (`as_i64()`, `as_str()`, etc.)
fn field_getter_code(ty: &Type) -> &'static str {
    match ty {
        Type::Int   => "as_i64()",
        Type::Float => "as_f64()",
        Type::Bool  => "as_bool()",
        Type::Str   => "as_str()",
    }
}

fn infer_field_getter(object: &Expr, field: &str, scope: &Scope) -> String {
    let var_name = match object { Expr::Var(n) => Some(n.as_str()), _ => None };

    if let Some(name) = var_name {
        if let Some(Binding::RowBinding(table)) = scope.get(name) {
            if let Some(ty) = scope.field_type(table, field) {
                return match ty {
                    Type::Str   => "as_str().unwrap_or(\"\").to_owned()".to_owned(),
                    Type::Int   => format!("as_i64().unwrap_or({})", ty.zero_rust()),
                    Type::Float => format!("as_f64().unwrap_or({})", ty.zero_rust()),
                    Type::Bool  => format!("as_bool().unwrap_or({})", ty.zero_rust()),
                };
            }
        }
    }
    "as_str().unwrap_or(\"\").to_owned()".to_owned()
}

fn coerce_to_json(code: &str, ty: &Type) -> String {
    match ty {
        Type::Str   => format!("serde_json::Value::String(({code}).to_string())"),
        Type::Int   => format!("serde_json::Value::Number(serde_json::Number::from({code} as i64))"),
        Type::Float => format!(
            "serde_json::Value::Number(serde_json::Number::from_f64({code} as f64)\
             .unwrap_or(serde_json::Number::from(0)))"
        ),
        Type::Bool  => format!("serde_json::Value::Bool({code} as i64 != 0)"),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dsl::lexer::tokenize;
    use crate::dsl::parser::parse;

    fn compile(src: &str) -> String {
        let tokens = tokenize(src).expect("lex");
        let program = parse(tokens).expect("parse");
        generate(&program).expect("codegen")
    }

    #[test]
    fn codegen_empty_reducer() {
        let out = compile("reducer reset() {}");
        assert!(out.contains("#[neondb::reducer]"));
        assert!(out.contains("fn reset(ctx: ReducerContext)"));
    }

    #[test]
    fn codegen_reducer_named_rust_keyword_is_escaped() {
        // `move` is a Rust keyword — the generated fn must be a raw identifier
        // (`fn r#move`) or it won't compile. The #[reducer] macro strips the
        // `r#` back off, so the wire name stays "move" for clients.
        let out = compile("reducer move(id: str, x: float) {}");
        assert!(out.contains("fn r#move(ctx: ReducerContext"),
            "keyword reducer name must be escaped as a raw identifier:\n{out}");
        assert!(!out.contains("fn move("),
            "must not emit the bare keyword `fn move(`");
    }

    #[test]
    fn codegen_non_keyword_name_not_escaped() {
        let out = compile("reducer attack(id: str) {}");
        assert!(out.contains("fn attack(ctx: ReducerContext"));
        assert!(!out.contains("r#attack"));
    }

    #[test]
    fn codegen_params_emitted() {
        let out = compile("reducer spawn(player_id: str, x: float) {}");
        assert!(out.contains("player_id: String"));
        assert!(out.contains("x: f64"));
    }

    #[test]
    fn codegen_assign_row() {
        let out = compile(r#"reducer spawn(id: str) { players[id] = { hp: 100, alive: true } }"#);
        assert!(out.contains("ctx.set(\"players\""));
        assert!(out.contains("serde_json::json!"));
    }

    #[test]
    fn codegen_delete_row() {
        let out = compile(r#"reducer despawn(id: str) { delete players[id] }"#);
        assert!(out.contains("ctx.delete(\"players\""));
    }

    #[test]
    fn codegen_let_row_with_else_error() {
        let out = compile(r#"
            reducer mv(id: str, x: float) {
                let p = players[id] else { error("not found") }
            }
        "#);
        assert!(out.contains("ctx.get(\"players\""));
        assert!(out.contains("not found"));
    }

    #[test]
    fn codegen_if_stmt() {
        let out = compile(r#"reducer check(hp: int) { if hp <= 0 { error("dead") } }"#);
        assert!(out.contains("if (hp <= 0i64)"));
        assert!(out.contains("dead"));
    }

    #[test]
    fn codegen_else_if() {
        let out = compile(r#"reducer tier(rank: int) {
            if rank == 1 { return { tier: "gold" } }
            else if rank == 2 { return { tier: "silver" } }
            else { return { tier: "bronze" } }
        }"#);
        assert!(out.contains("} else if (rank == 2i64)"));
        assert!(out.contains("} else {"));
    }

    #[test]
    fn codegen_return_row_literal() {
        let out = compile(r#"reducer info(id: str) { return { ok: true } }"#);
        assert!(out.contains("neondb::ret!"));
        assert!(out.contains("\"ok\":"));
    }

    #[test]
    fn codegen_caller_id_global() {
        let out = compile(r#"reducer who() { let id = caller_id }"#);
        assert!(out.contains("ctx.caller_id.clone()"));
    }

    #[test]
    fn codegen_assign_field() {
        let out = compile(r#"reducer heal(id: str, amt: int) { players[id].hp = amt }"#);
        assert!(out.contains("ctx.get(\"players\""));
        assert!(out.contains("ctx.set(\"players\""));
        assert!(out.contains("\"hp\""));
    }

    #[test]
    fn codegen_assign_field_op() {
        let out = compile(r#"reducer take_damage(id: str, dmg: int) { players[id].hp -= dmg }"#);
        assert!(out.contains("__old_hp"));
        assert!(out.contains("- (dmg)"));
    }

    #[test]
    fn codegen_for_row_loop() {
        let out = compile(r#"reducer cleanup() { for id, p in players { delete players[id] } }"#);
        assert!(out.contains("list_rows_with_keys(\"players\")"));
        assert!(out.contains("ctx.delete(\"players\""));
    }

    #[test]
    fn codegen_for_array_loop() {
        let out = compile(r#"reducer x(id: str) {
            let p = players[id] else { error("x") }
            for item in p.inventory { let n = item }
        }"#);
        assert!(out.contains("as_array().cloned().unwrap_or_default()"));
        assert!(out.contains("for item in __arr_item_"));
    }

    #[test]
    fn codegen_while_loop() {
        let out = compile(r#"reducer x(n: int) { while n > 0 { let n = n - 1 } }"#);
        assert!(out.contains("while (n > 0i64)"));
    }

    #[test]
    fn codegen_break_continue() {
        let out = compile(r#"reducer x() { while true { break } }"#);
        assert!(out.contains("break;"));
    }

    #[test]
    fn codegen_array_literal() {
        let out = compile(r#"reducer x() { let arr = [1, 2, 3] }"#);
        assert!(out.contains("serde_json::Value::Array"));
        assert!(out.contains("1i64"));
        assert!(out.contains("2i64"));
    }

    #[test]
    fn codegen_modulo() {
        let out = compile(r#"reducer x(n: int) { let r = n % 2 }"#);
        assert!(out.contains("% 2i64"));
    }

    #[test]
    fn codegen_bitwise() {
        let out = compile(r#"reducer x(a: int, b: int) { let r = a & b }"#);
        assert!(out.contains("& b)"));
    }

    #[test]
    fn codegen_shift() {
        let out = compile(r#"reducer x(a: int) { let r = a << 2 }"#);
        assert!(out.contains("<< 2i64"));
    }

    #[test]
    fn codegen_timestamp() {
        let out = compile(r#"reducer ts() { let t = timestamp() }"#);
        assert!(out.contains("ctx.timestamp()"));
    }

    #[test]
    fn codegen_counter_get() {
        let out = compile(r#"reducer kills() { let k = counter("kills") }"#);
        assert!(out.contains("ctx.get_counter"));
    }

    #[test]
    fn codegen_set_counter() {
        let out = compile(r#"reducer add_kill() { set_counter("kills", 1) }"#);
        assert!(out.contains("ctx.set_counter"));
        assert!(out.contains("kills"));
    }

    #[test]
    fn codegen_min_max() {
        let out = compile(r#"reducer clamp_hp(a: int, b: int) { let m = min(a, b) }"#);
        assert!(out.contains(".min("));
    }

    #[test]
    fn codegen_math_builtins() {
        let out = compile(r#"reducer calc(x: float) { let a = abs(x) let f = floor(x) let c = ceil(x) let s = sqrt(x) }"#);
        assert!(out.contains(".abs()"));
        assert!(out.contains(".floor()"));
        assert!(out.contains(".ceil()"));
        assert!(out.contains(".sqrt()"));
    }

    #[test]
    fn codegen_string_builtins() {
        let out = compile(r#"reducer greet(name: str) { let s = to_upper(name) let t = trim(s) }"#);
        assert!(out.contains(".to_uppercase()"));
        assert!(out.contains(".trim()"));
    }

    #[test]
    fn codegen_type_casts() {
        let out = compile(r#"reducer cast(x: float) { let i = int(x) let s = str(x) }"#);
        assert!(out.contains("as i64"));
        assert!(out.contains(".to_string()"));
    }

    #[test]
    fn codegen_rand_int() {
        let out = compile(r#"reducer roll(lo: int, hi: int) { let r = rand_int(lo, hi) }"#);
        assert!(out.contains("ctx.timestamp()"));
    }

    #[test]
    fn codegen_concat() {
        let out = compile(r#"reducer greet(name: str) { let s = concat("Hello, ", name) }"#);
        assert!(out.contains("format!"));
    }

    #[test]
    fn codegen_string_ops() {
        let out = compile(r#"reducer x(s: str) {
            let parts = split(s, ",")
            let idx   = index_of(s, "x")
            let sub   = substring(s, 0, 3)
        }"#);
        assert!(out.contains(".split("));
        assert!(out.contains(".find("));
        assert!(out.contains(".chars().skip("));
    }

    #[test]
    fn codegen_array_ops() {
        let out = compile(r#"reducer x() {
            let arr = [1, 2, 3]
            let n   = array_len(arr)
            let v   = get_index(arr, 0)
        }"#);
        assert!(out.contains("as_array().map(|__v| __v.len()"));
        assert!(out.contains(".as_array().and_then(|__v| __v.get("));
    }

    #[test]
    fn codegen_push_pop() {
        let out = compile(r#"reducer x() {
            let arr = [1, 2]
            push(arr, 3)
            pop(arr)
        }"#);
        assert!(out.contains("__push_v"));
        assert!(out.contains("__pop_v"));
    }

    #[test]
    fn codegen_table_queries() {
        let out = compile(r#"reducer stats() {
            let n  = count_rows("players")
            let s  = sum_field("players", "score")
            let av = avg_field("players", "score")
        }"#);
        assert!(out.contains("list_rows_with_keys("));
        assert!(out.contains(".sum::<f64>()"));
    }

    #[test]
    fn codegen_find_and_sort() {
        let out = compile(r#"reducer x() {
            let top  = top_n("players", "score", 10)
            let rows = sort_by("players", "hp", "desc")
            let p    = find_first("players", "alive", true)
        }"#);
        assert!(out.contains(".take(__n)"));
        assert!(out.contains("__dir == \"desc\""));
        assert!(out.contains(".find(|(_, __r)|"));
    }

    #[test]
    fn codegen_let_mut_emitted() {
        let out = compile(r#"reducer x(n: int) { let v = n + 1 }"#);
        assert!(out.contains("let mut v ="), "let mut not emitted: {out}");
    }

    #[test]
    fn codegen_smoke_neon_file() {
        let src = include_str!("tests/smoke_test.neon");
        let tokens = tokenize(src).expect("lex smoke");
        let program = parse(tokens).expect("parse smoke");
        let out = generate(&program).expect("codegen smoke");
        // All 8 reducers present
        for name in &["spawn", "move_player", "take_damage", "heal", "add_kill",
                       "cleanup_dead", "get_stats", "roll_loot"] {
            assert!(out.contains(&format!("fn {name}(")), "missing reducer {name}");
        }
        // Key generated constructs
        assert!(out.contains("list_rows_with_keys(\"players\")?"), "for loop missing ?");
        assert!(out.contains("ctx.set_counter"),   "set_counter missing");
        assert!(out.contains("ctx.get_counter"),   "counter() missing");
        assert!(out.contains("ctx.timestamp()"),   "timestamp missing");
        assert!(out.contains(".max("),             "max() missing");
        assert!(out.contains("__ts ^ (__ts >> 33)"), "rand_int expansion missing");
    }

    #[test]
    fn codegen_multiple_reducers() {
        let out = compile(r#"
            reducer a() {}
            reducer b(x: int) {}
        "#);
        assert!(out.contains("fn a("));
        assert!(out.contains("fn b("));
    }

    #[test]
    fn codegen_error_stmt() {
        let out = compile(r#"reducer fail() { error("boom") }"#);
        assert!(out.contains("NeonDBError::reducer_error"));
        assert!(out.contains("boom"));
    }

    #[test]
    fn codegen_mmo_full_test_neon() {
        let src = include_str!("tests/mmo_full_test.neon");
        let tokens = tokenize(src).expect("lex mmo");
        let program = parse(tokens).expect("parse mmo");
        let out = generate(&program).expect("codegen mmo");

        // Verify all major reducer categories compiled
        for name in &["spawn", "take_damage", "heal", "grant_xp", "roll_loot",
                       "open_loot_box", "create_guild", "join_guild", "cleanup_dead",
                       "get_stats", "leaderboard", "find_player_by_name",
                       "find_guild_members", "update_name", "grant_flag", "has_flag",
                       "server_economy"] {
            assert!(out.contains(&format!("fn {name}(")), "missing: {name}");
        }

        // while loop
        assert!(out.contains("while ("), "while loop missing");
        // else if
        assert!(out.contains("} else if ("), "else if missing");
        // bitwise ops
        assert!(out.contains("& 7i64") || out.contains("& flag)"), "bitwise AND missing");
        // modulo
        assert!(out.contains("% 10i64"), "modulo missing");
        // shift
        assert!(out.contains("<< 2i64"), "shift missing");
        // array literal
        assert!(out.contains("serde_json::Value::Array(vec!["), "array literal missing");
        // table queries
        assert!(out.contains("count_rows") || out.contains("list_rows_with_keys"), "count_rows missing");
        assert!(out.contains(".take(__n)"), "top_n missing");
        assert!(out.contains(".sum::<f64>()"), "sum_field missing");
        // string ops
        assert!(out.contains(".split("), "split missing");
        assert!(out.contains(".chars().skip("), "substring missing");
        // for array loop
        assert!(out.contains("as_array().cloned().unwrap_or_default()"), "ForArray missing");
    }
}
