use std::path::Path;

use crate::error::{Result, VoltraError};

pub struct TableInfo {
    pub name: String,
    pub fields: Vec<(String, String)>,
}

pub struct ReducerInfo {
    pub name: String,
    pub params: Vec<(String, String)>,
}

pub fn generate(
    lang: &str,
    out: &Path,
    tables: &[TableInfo],
    reducers: &[ReducerInfo],
) -> Result<()> {
    std::fs::create_dir_all(out)
        .map_err(|e| VoltraError::internal(format!("Cannot create output dir: {}", e)))?;
    match lang {
        "typescript" | "ts" => generate_typescript(out, tables, reducers),
        "csharp" | "cs" => generate_csharp(out, tables, reducers),
        "gdscript" | "gd" => generate_gdscript(out, tables, reducers),
        other => Err(VoltraError::invalid_argument(format!(
            "Unknown --lang '{}'. Supported: typescript, csharp, gdscript",
            other
        ))),
    }
}

fn write_file(out: &Path, name: &str, content: &str) -> Result<()> {
    let path = out.join(name);
    std::fs::write(&path, content)
        .map_err(|e| VoltraError::internal(format!("Cannot write {}: {}", path.display(), e)))
}

fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}

fn ts_type(t: &str) -> &str {
    match t.to_lowercase().as_str() {
        "string" | "str" | "text" => "string",
        "i64" | "i32" | "int" | "integer" | "number" => "number",
        "f64" | "f32" | "float" | "double" => "number",
        "bool" | "boolean" => "boolean",
        "bytes" | "blob" => "Uint8Array",
        _ => "unknown",
    }
}

fn cs_type(t: &str) -> &str {
    match t.to_lowercase().as_str() {
        "string" | "str" | "text" => "string",
        "i64" | "int" | "integer" => "long",
        "i32" | "number" => "int",
        "f64" | "double" | "float" => "double",
        "bool" | "boolean" => "bool",
        "bytes" | "blob" => "byte[]",
        _ => "object",
    }
}

fn gd_type(t: &str) -> &str {
    match t.to_lowercase().as_str() {
        "string" | "str" | "text" => "String",
        "i64" | "i32" | "int" | "integer" | "number" => "int",
        "f64" | "f32" | "float" | "double" => "float",
        "bool" | "boolean" => "bool",
        "bytes" | "blob" => "PackedByteArray",
        _ => "Variant",
    }
}

fn generate_typescript(out: &Path, tables: &[TableInfo], reducers: &[ReducerInfo]) -> Result<()> {
    let mut ts = String::from("// AUTO-GENERATED by `voltra generate` — DO NOT EDIT\n\n");
    for t in tables {
        let pascal = to_pascal(&t.name);
        ts.push_str(&format!("export interface {} {{\n", pascal));
        for (field, typ) in &t.fields {
            ts.push_str(&format!("  {}: {};\n", field, ts_type(typ)));
        }
        ts.push_str("}\n\n");
    }

    ts.push_str("import type { VoltraClient } from 'voltra-client';\n\n");
    ts.push_str("export const Reducers = {\n");
    for r in reducers {
        let camel = {
            let mut p = to_pascal(&r.name);
            if let Some(f) = p.get_mut(0..1) {
                f.make_ascii_lowercase();
            }
            p
        };
        let args = r
            .params
            .iter()
            .map(|(n, _)| n.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        ts.push_str(&format!(
            "  {}(db: VoltraClient, {}): Promise<unknown> {{\n    return db.call('{}', [{}]);\n  }},\n",
            camel, args, r.name, args,
        ));
    }
    ts.push_str("};\n");

    write_file(out, "tables.ts", &ts)?;
    println!(
        "TypeScript: wrote {}/tables.ts ({} table(s), {} reducer(s))",
        out.display(),
        tables.len(),
        reducers.len()
    );
    Ok(())
}

fn generate_csharp(out: &Path, tables: &[TableInfo], reducers: &[ReducerInfo]) -> Result<()> {
    let mut cs = String::from(
        "// AUTO-GENERATED by `voltra generate` — DO NOT EDIT\nusing System;\nusing System.Threading.Tasks;\n\n",
    );
    for t in tables {
        let pascal = to_pascal(&t.name);
        cs.push_str(&format!("public class {} {{\n", pascal));
        for (field, typ) in &t.fields {
            cs.push_str(&format!(
                "    public {} {} {{ get; set; }}\n",
                cs_type(typ),
                to_pascal(field)
            ));
        }
        cs.push_str("}\n\n");
    }

    cs.push_str("public static class Reducers {\n");
    for r in reducers {
        let params_str = r
            .params
            .iter()
            .map(|(n, t)| format!("{} {}", cs_type(t), to_pascal(n)))
            .collect::<Vec<_>>()
            .join(", ");
        cs.push_str(&format!(
            "    public static async Task<object?> {}(VoltraClient db, {})\n",
            to_pascal(&r.name),
            params_str,
        ));
        cs.push_str(&format!(
            "        => await db.Call(\"{}\", new object[] {{ {} }});\n\n",
            r.name,
            r.params
                .iter()
                .map(|(n, _)| to_pascal(n))
                .collect::<Vec<_>>()
                .join(", "),
        ));
    }
    cs.push_str("}\n");

    write_file(out, "Tables.cs", &cs)?;
    println!(
        "C#: wrote {}/Tables.cs ({} table(s), {} reducer(s))",
        out.display(),
        tables.len(),
        reducers.len()
    );
    Ok(())
}

fn generate_gdscript(out: &Path, tables: &[TableInfo], reducers: &[ReducerInfo]) -> Result<()> {
    let mut gd = String::from("# AUTO-GENERATED by `voltra generate` — DO NOT EDIT\n\n");
    for t in tables {
        let pascal = to_pascal(&t.name);
        gd.push_str(&format!("class {}:\n", pascal));
        for (field, typ) in &t.fields {
            gd.push_str(&format!("    var {}: {}\n", field, gd_type(typ)));
        }
        gd.push('\n');
    }

    gd.push_str("class_name VoltraReducers\n\n");
    for r in reducers {
        let args = r
            .params
            .iter()
            .map(|(n, _)| n.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        gd.push_str(&format!(
            "static func {}(db, {}):\n    return await db.call_reducer(\"{}\", [{}])\n\n",
            r.name, args, r.name, args,
        ));
    }

    write_file(out, "tables.gd", &gd)?;
    println!(
        "GDScript: wrote {}/tables.gd ({} table(s), {} reducer(s))",
        out.display(),
        tables.len(),
        reducers.len()
    );
    Ok(())
}
