// ============================================================================
// src/hlc.rs — Hybrid Logical Clock
//
// Provides monotonically increasing timestamps that are consistent across
// cluster nodes even in the presence of wall-clock drift or backward jumps.
//
// ## Encoding
//
//   u64 = [ physical_ms : 48 bits ][ logical : 16 bits ]
//
//   physical_ms — wall-clock milliseconds since UNIX epoch (supports ~8 900 years)
//   logical     — tie-breaker counter within the same millisecond
//
// Comparison is pure integer comparison: higher u64 = later event.
//
// ## Algorithm (Kulkarni et al. 2014)
//
//   send/local event:
//     new.physical = max(local.physical, wall_ms)
//     new.logical  = if new.physical == local.physical { local.logical + 1 } else { 0 }
//
//   receive event (msg carries hlc_ts):
//     new.physical = max(local.physical, msg.physical, wall_ms)
//     new.logical  = if all three physicals equal { max(locals) + 1 }
//                    else if new.physical == msg.physical { msg.logical + 1 }
//                    else if new.physical == local.physical { local.logical + 1 }
//                    else { 0 }
//
// ## Usage in NeonDB
//
//   - Every committed `RowDelta` carries an `hlc_ts` generated by the local clock.
//   - When a node receives deltas from a cluster peer, it calls `HlcClock::receive`
//     to advance its own clock past the sender's timestamp.
//   - `apply_delta_batch` uses HLC comparison for last-write-wins resolution on
//     cross-shard `insert`/`update` operations: a delta whose HLC is older than
//     the row's stored HLC is silently skipped (stale write).
// ============================================================================

use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

// ─────────────────────────────────────────────────────────────────────────────
// HlcTimestamp — packed u64
// ─────────────────────────────────────────────────────────────────────────────

/// A Hybrid Logical Clock timestamp packed into a `u64`.
///
/// Top 48 bits: wall-clock milliseconds.
/// Bottom 16 bits: logical counter (tie-breaker within one millisecond).
///
/// Integer comparison is equivalent to causal ordering: `a < b` means `a`
/// happened before `b` (or is unrelated but receives a lower causal rank).
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Default)]
pub struct HlcTimestamp(pub u64);

impl HlcTimestamp {
    /// Pack wall-clock ms + logical counter into a single u64.
    #[inline]
    pub fn pack(wall_ms: u64, logical: u16) -> Self {
        HlcTimestamp((wall_ms << 16) | (logical as u64))
    }

    /// Wall-clock component in milliseconds.
    #[inline]
    pub fn wall_ms(self) -> u64 {
        self.0 >> 16
    }

    /// Logical counter component.
    #[inline]
    pub fn logical(self) -> u16 {
        (self.0 & 0xFFFF) as u16
    }

    /// The zero / "unset" timestamp.
    pub const ZERO: HlcTimestamp = HlcTimestamp(0);

    /// Raw packed value (suitable for storing in `RowDelta.hlc_ts`).
    #[inline]
    pub fn raw(self) -> u64 {
        self.0
    }
}

impl From<u64> for HlcTimestamp {
    fn from(v: u64) -> Self {
        HlcTimestamp(v)
    }
}

impl std::fmt::Display for HlcTimestamp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}+{}", self.wall_ms(), self.logical())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// HlcClock — process-wide, lock-free
// ─────────────────────────────────────────────────────────────────────────────

/// A lock-free Hybrid Logical Clock.
///
/// `HlcClock` is safe to share across threads via `Arc<HlcClock>`.
/// All operations are CAS loops on a single `AtomicU64` — no mutex, no
/// allocation, and typically a single CAS succeeds on the first try.
pub struct HlcClock {
    last: AtomicU64,
}

impl Default for HlcClock {
    fn default() -> Self {
        Self::new()
    }
}

impl HlcClock {
    /// Create a new clock starting at zero.
    pub fn new() -> Self {
        HlcClock {
            last: AtomicU64::new(0),
        }
    }

    /// Read current wall-clock milliseconds.
    fn wall_now() -> u64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64
    }

    /// Generate a new timestamp for a local event (reducer commit, write, etc.).
    ///
    /// Guarantees: the returned timestamp is strictly greater than any previously
    /// returned timestamp, even if the wall clock goes backward.
    pub fn now(&self) -> HlcTimestamp {
        let wall = Self::wall_now();
        loop {
            let last = HlcTimestamp(self.last.load(Ordering::Acquire));
            let new = if wall > last.wall_ms() {
                // Clock advanced — reset logical counter.
                HlcTimestamp::pack(wall, 0)
            } else {
                // Same millisecond or clock went backward — bump logical.
                HlcTimestamp::pack(
                    last.wall_ms(),
                    last.logical().saturating_add(1),
                )
            };
            if self
                .last
                .compare_exchange(last.0, new.0, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
            {
                return new;
            }
        }
    }

    /// Update the clock upon receiving a message from a remote node.
    ///
    /// Returns a new timestamp that is strictly greater than both the local
    /// clock and the received timestamp, ensuring causal consistency.
    ///
    /// Call this whenever a `RowDelta` arrives via cluster fanout before
    /// applying the delta to the local `TableStore`.
    pub fn receive(&self, received: HlcTimestamp) -> HlcTimestamp {
        let wall = Self::wall_now();
        loop {
            let last = HlcTimestamp(self.last.load(Ordering::Acquire));

            let max_wall = wall.max(received.wall_ms()).max(last.wall_ms());

            let new = if max_wall > received.wall_ms() && max_wall > last.wall_ms() {
                // Local wall clock is ahead of everything — reset logical.
                HlcTimestamp::pack(max_wall, 0)
            } else if received.wall_ms() == last.wall_ms() {
                // Both remote and local are in the same ms — take the higher logical + 1.
                HlcTimestamp::pack(
                    max_wall,
                    received.logical().max(last.logical()).saturating_add(1),
                )
            } else if received > last {
                // Remote is strictly ahead — step past it.
                HlcTimestamp::pack(received.wall_ms(), received.logical().saturating_add(1))
            } else {
                // Local is ahead — just bump logical.
                HlcTimestamp::pack(last.wall_ms(), last.logical().saturating_add(1))
            };

            if self
                .last
                .compare_exchange(last.0, new.0, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
            {
                return new;
            }
        }
    }

    /// Return the current clock value without advancing it.
    pub fn peek(&self) -> HlcTimestamp {
        HlcTimestamp(self.last.load(Ordering::Acquire))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pack_unpack_roundtrip() {
        let ts = HlcTimestamp::pack(1_700_000_000_000, 42);
        assert_eq!(ts.wall_ms(), 1_700_000_000_000);
        assert_eq!(ts.logical(), 42);
    }

    #[test]
    fn ordering_wall_clock_dominates() {
        let a = HlcTimestamp::pack(100, 999);
        let b = HlcTimestamp::pack(101, 0);
        assert!(b > a, "higher wall clock must beat higher logical");
    }

    #[test]
    fn ordering_logical_breaks_ties() {
        let a = HlcTimestamp::pack(100, 5);
        let b = HlcTimestamp::pack(100, 6);
        assert!(b > a);
    }

    #[test]
    fn clock_now_is_monotonic() {
        let clock = HlcClock::new();
        let mut prev = clock.now();
        for _ in 0..1000 {
            let next = clock.now();
            assert!(next > prev, "clock must be strictly monotonic");
            prev = next;
        }
    }

    #[test]
    fn clock_receive_advances_past_remote() {
        let clock = HlcClock::new();
        // Simulate a remote timestamp far in the future.
        let far_future = HlcTimestamp::pack(9_999_999_999_999, 7);
        let after = clock.receive(far_future);
        assert!(after > far_future, "local clock must advance past the received timestamp");
    }

    #[test]
    fn clock_receive_idempotent_for_old_messages() {
        let clock = HlcClock::new();
        let t1 = clock.now();
        // Receiving a very old message must not roll the clock backward.
        let old = HlcTimestamp::pack(1, 0);
        let t2 = clock.receive(old);
        assert!(t2 > t1);
    }

    #[test]
    fn concurrent_now_calls_are_unique() {
        use std::collections::HashSet;
        use std::sync::Arc;
        let clock = Arc::new(HlcClock::new());
        let threads: Vec<_> = (0..8).map(|_| {
            let c = clock.clone();
            std::thread::spawn(move || {
                (0..1000).map(|_| c.now().raw()).collect::<Vec<_>>()
            })
        }).collect();
        let mut all: Vec<u64> = threads.into_iter().flat_map(|h| h.join().unwrap()).collect();
        let len = all.len();
        all.sort_unstable();
        all.dedup();
        assert_eq!(all.len(), len, "all HLC timestamps must be unique across threads");
    }

    #[test]
    fn zero_constant_is_zero() {
        assert_eq!(HlcTimestamp::ZERO.raw(), 0);
        assert_eq!(HlcTimestamp::ZERO.wall_ms(), 0);
        assert_eq!(HlcTimestamp::ZERO.logical(), 0);
    }
}
