pub mod admin;
pub mod auth;
pub mod auth_service;
pub mod backup;
pub mod cli;
pub mod cluster;
pub mod codegen;
pub mod compression;
pub mod config;
pub mod dsl;
pub mod error;
pub mod leaderboard;
pub mod metrics;
pub mod migrations;
pub mod mvcc;
pub mod network;
pub mod persistence;
pub mod persistent;
pub mod pg;
pub mod presence;
pub mod redis;
pub mod reducer;
pub mod replication;
pub mod runtime;
pub mod schema;
pub mod server;
pub mod sql;
pub mod stat_sync;
pub mod subscriptions;
pub mod table;
pub mod tenant;
pub mod tracing_setup;
pub mod ttl;
pub mod updater;
pub mod wal;
pub mod worker_pool;

/// Release generation. The most-significant component of Voltra's version: a
/// generation groups a line of releases, and resets the numeric version to
/// 1.0.0. Release tags are `g<GENERATION>.<major>.<minor>.<patch>`
/// (e.g. `g1.1.0.0`). The updater treats generation as the highest-priority
/// component, so a generation bump always supersedes the previous line.
/// See VERSIONING.md.
pub const GENERATION: u32 = 1;
/// Human-readable codename for the current [`GENERATION`].
pub const GENERATION_CODENAME: &str = "Genesis";

pub use error::{Result, VoltraError};
pub use network::{
    start_listener, ClientMessage, PendingCall, ReducerCall, ReducerResponse, ServerMessage,
    SubscriptionDiff,
};
pub use reducer::{increment_reducer, IncrementResult, ReducerContext, ReducerRegistry};
pub use schema::{ColumnDef, ColumnType, SchemaRegistry, TableSchema};
pub use server::{run_server, run_server_blocking, run_server_with_handle, ServerHandle};
pub use sql::{Executor as SqlExecutor, QueryResult as SqlQueryResult};
pub use subscriptions::{ClientId, SubscriptionManager};
pub use table::TableStore;
pub use tenant::{logical_table, physical_table, TenantInfo, TenantRegistry};
pub use wal::{SnapshotMeta, WalEntry, WalReader, WalWriter};

// ── Memory reclamation ──────────────────────────────────────────────────────

/// Spawn a background task that periodically forces mimalloc to return retained
/// (freed-but-cached) memory back to the OS via `mi_collect(true)`.
///
/// Under sustained high write throughput the allocator accumulates a large pool
/// of freed pages it holds for reuse (this is normally good for speed). At tens
/// of thousands of concurrent connections that retained pool, plus periodic
/// snapshot-clone spikes, inflates the process RSS by hundreds of MB to GBs even
/// though the live working set is far smaller. Forcing a collect on an interval
/// returns that memory to the OS, holding RSS near the live-data floor rather
/// than the churn peak — the difference between fitting 15-20K CCU in a given
/// RAM budget and OOMing.
///
/// Cheap relative to the work it bounds; the default interval keeps overhead
/// negligible while still reclaiming promptly after snapshot spikes.
#[cfg(feature = "mimalloc")]
pub fn spawn_memory_reclaimer(interval_secs: u64) {
    let interval = interval_secs.max(1);
    tokio::spawn(async move {
        let mut ticker = tokio::time::interval(std::time::Duration::from_secs(interval));
        ticker.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        loop {
            ticker.tick().await;
            // SAFETY: mi_collect is a thread-safe, side-effect-only call into the
            // mimalloc runtime. `force = true` reclaims abandoned segments and
            // decommits cached pages back to the OS.
            unsafe {
                libmimalloc_sys::mi_collect(true);
            }
        }
    });
}

/// No-op when the mimalloc allocator feature is disabled (system allocator has
/// no equivalent manual-reclaim hook).
#[cfg(not(feature = "mimalloc"))]
pub fn spawn_memory_reclaimer(_interval_secs: u64) {}

/// Current wall-clock time in nanoseconds since the Unix epoch (0 on error).
pub fn now_nanos() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0)
}

// ── Macro support ─────────────────────────────────────────────────────────────

/// Re-export `inventory` so the code generated by `#[reducer]` and
/// `#[table]` can reach `::voltra::inventory::submit!` without requiring
/// users to add `inventory` as a direct dependency.
#[doc(hidden)]
pub use inventory;

/// Re-export `rmp_serde` so the `ret!` macro can use `$crate::rmp_serde`
/// without requiring users to add `rmp_serde` as a direct dependency.
#[doc(hidden)]
pub use rmp_serde;

// Re-export the attribute macros so users can write `#[voltra::reducer]`
// or `use voltra::reducer` after `use voltra::*`.
pub use voltra_macros::{reducer, table};

/// Return a JSON result from a `#[reducer]` function.
///
/// Encodes the given JSON literal (using `serde_json::json!`) as MessagePack
/// and returns it from the surrounding reducer function.  Uses early `return`,
/// so it must be used inside a `#[reducer]`-annotated function body.
///
/// # Example
/// ```rust,ignore
/// #[reducer]
/// fn heal(ctx: Ctx, target_id: String, amount: i32) {
///     // ... modify row ...
///     ret!({ "ok": true, "new_hp": new_hp })
/// }
/// ```
#[macro_export]
macro_rules! ret {
    ($($json:tt)*) => {{
        let __ret_bytes = $crate::rmp_serde::to_vec(&::serde_json::json!($($json)*))
            .map_err(|e| $crate::error::VoltraError::reducer_error(e.to_string()))?;
        return Ok(__ret_bytes);
    }};
}
