pub mod auth;
pub mod backup;
pub mod cluster;
pub mod metrics;
pub mod chat;
pub mod tenant;
pub mod cli;
pub mod config;
pub mod error;
pub mod leaderboard;
pub mod matchmaking;
pub mod migrations;
pub mod mvcc;
pub mod network;
pub mod redis;
pub mod persistence;
pub mod pg;
pub mod presence;
pub mod reducer;
pub mod replication;
pub mod runtime;
pub mod stat_sync;
pub mod schema;
pub mod sql;
pub mod subscriptions;
pub mod table;
pub mod ttl;
pub mod wal;
pub mod server;
pub mod updater;
pub mod worker_pool;

pub use error::{NeonDBError, Result};
pub use tenant::{TenantRegistry, TenantInfo, physical_table, logical_table};
pub use network::{
    start_listener, ClientMessage, PendingCall, ReducerCall, ReducerResponse, ServerMessage,
    SubscriptionDiff,
};
pub use server::{run_server, run_server_blocking, run_server_with_handle, ServerHandle};
pub use reducer::{increment_reducer, IncrementResult, ReducerContext, ReducerRegistry};
pub use schema::{SchemaRegistry, TableSchema, ColumnDef, ColumnType};
pub use sql::{Executor as SqlExecutor, QueryResult as SqlQueryResult};
pub use subscriptions::{ClientId, SubscriptionManager};
pub use table::TableStore;
pub use wal::{SnapshotMeta, WalEntry, WalReader, WalWriter};

// ── Macro support ─────────────────────────────────────────────────────────────

/// Re-export `inventory` so the code generated by `#[reducer]` and
/// `#[table]` can reach `::neondb::inventory::submit!` without requiring
/// users to add `inventory` as a direct dependency.
#[doc(hidden)]
pub use inventory;

/// Re-export `rmp_serde` so the `ret!` macro can use `$crate::rmp_serde`
/// without requiring users to add `rmp_serde` as a direct dependency.
#[doc(hidden)]
pub use rmp_serde;

// Re-export the attribute macros so users can write `#[neondb::reducer]`
// or `use neondb::reducer` after `use neondb::*`.
pub use neondb_macros::{reducer, table};

/// Return a JSON result from a `#[reducer]` function.
///
/// Encodes the given JSON literal (using `serde_json::json!`) as MessagePack
/// and returns it from the surrounding reducer function.  Uses early `return`,
/// so it must be used inside a `#[reducer]`-annotated function body.
///
/// # Example
/// ```rust,ignore
/// #[reducer]
/// fn heal(ctx: Ctx, target_id: String, amount: i32) {
///     // ... modify row ...
///     ret!({ "ok": true, "new_hp": new_hp })
/// }
/// ```
#[macro_export]
macro_rules! ret {
    ($($json:tt)*) => {{
        let __ret_bytes = $crate::rmp_serde::to_vec(&::serde_json::json!($($json)*))
            .map_err(|e| $crate::error::NeonDBError::reducer_error(e.to_string()))?;
        return Ok(__ret_bytes);
    }};
}
